import Image from "next/image";
import { Button } from "../components/Button";
import { Footer } from "../components/Footer";
import { NavBar } from "../components/NavBar";

export default function Home() {
  return (
    <main>
      <NavBar />

      <Hero />

      <div className="flex flex-col items-center gap-y-2 px-10 py-20 text-center">
        <p className="font-garamond text-2xl">
          Subscribe to the Starving Artist Myth Newsletter and receive a free
          excerpt.
        </p>
        <p className="text-md font-garamond">
          Plus, get a discount code worth 10% off purchase of the book from the
          Dundurn Press Online Store
        </p>
        <p className="font-garamond text-xs">(conditions apply)</p>

        <Button className="my-3" href="/" label="Subscribe" />
      </div>

      <Footer />
    </main>
  );
}

function Hero() {
  return (
    <div className="bg-hero flex min-w-[375px] flex-col items-center justify-center px-6 py-10 font-interstate text-xl text-black lg:flex-row lg:gap-8 lg:px-12 lg:py-20 lg:text-2xl">
      <div className="relative aspect-square min-w-[300px] md:min-w-[400px]">
        <Image
          alt="book"
          sizes="100vw"
          objectFit="contain"
          fill
          src="/starving-artist-render.png"
        />
      </div>

      <div className="flex max-w-3xl flex-col justify-center gap-y-8">
        <div className="flex flex-col gap-2">
          <h2 className="">
            “Mark Jones has written a classic. Accessible and erudite, laden
            with facts about the economic impact generated by ‘creative
            clusters’ and peppered with insights from diverse creators, this
            book shatters, once and for all, the myth of the starving artist.”
          </h2>
          <h3 className="font-interstate-black text-xl uppercase tracking-[.05em]">
            — Ana Serrano,
            <br /> President and Vice-Chancellor, OCAD University
          </h3>
        </div>

        <div className="flex flex-col gap-4">
          <p className="">
            In The Starving Artist Myth, Mark J. Jones addresses the doubt about
            opportunities in the creative economy by getting at the roots of the
            stereotype and answering the what, the why, and the how of achieving
            career goals. Featuring interviews of artists across the spectrum of
            creative fields and a practical career guide, The Starving Artist
            Myth lays out a manual for creative career success in a
            post-pandemic world.
          </p>
          <p className="">
            Mark J. Jones is the Dean of The Faculty of Animation, Arts, and
            Design at Sheridan College.
          </p>
          <p className="mt-3 font-interstate-black text-3xl uppercase tracking-widest">
            Available August 20, 2024
          </p>
        </div>

        <Button
          href="https://linktr.ee/starvingartistmyth"
          label="Pre-order here"
        />

        <Image
          className=""
          alt="book"
          src="/dundurn.png"
          height={150}
          width={150}
        />
      </div>
    </div>
  );
}
